### PR TITLE
Adapt to latest changes of Aptoide.com

### LINKED ISSUE #9: Download site not found
When asked "Insert link or package id", I inserted `com.facebook.katana` and then there was an error:

> Download site not found.

By the way, if we insert a link like https://facebook.en.aptoide.com/app there is another error:

> This is not a valid Aptoide URL.

### PR DESCRIPTION
**Pull request by bastei**
* use the api of aptoide.com to get apps by package name
* get the download URL directly from HTML/JSON
* use "Aptoide" as user agent as AptoideLite seems to be dead

fixes #9

### CODE REVIEW

**Comment by StefanescuCristian** [comment]
I don't have an Android device anymore, have you tested this, is it working?

**Comment by baptx** [comment]
@StefanescuCristian I don't have an Android device either but the shell script should work on desktop Linux, right? In the issue I reported, I tested on my computer.
When I need to test Android apps, I use Anbox (which is now deprecated in favor of Waydroid but without webcam support) or Android-x86 (on VirtualBox).

**Comment by bastei** [comment]
> Android device anymore, have you tested this, is it working?

Yes, I tested it on Android (LineageOS) and it works, although HOME-folder detection could be further improved.

**Comment by baptx** [comment]
I see the function `get_real_link_by_normal_link` was removed which had interesting content like this comment:

> Try to find the real mobile link by normal aptoide link (https://desired-package-id.en.aptoide.com/?store_name=somestore&app_id=xxxxxxxx)

Another function `get_real_link` was removed as well, which had this comment:

> Try to find the real mobile link by package id (and optional store name + app id)

But if we try to download the old version of an Android app like Facebook (for example with the URL https://facebook.en.aptoide.com/app?store_name=aptoide-web&app_id=64240156), it downloads the last version instead.

I would like to download an old version of Facebook because the last version stopped working on Anbox and before the automatic update, it was still possible to use the old version.

So it looks like it is a regression because according to the comments, it was technically possible to download old versions in the past (the app ID changes for each version). Let me know if my original issue can be reopened or if we should create a new one.

**Comment by bastei** [comment]
> But if we try to download the old version of an Android app like Facebook (for example with the URL https://facebook.en.aptoide.com/app?store_name=aptoide-web&app_id=64240156), it downloads the last version instead.

For me it downloads 400.0.0.16.76 for that URL which is not the latest version but the one that is displayed when opening that URL in the browser. Can you specify the problem you are running into?

Concerning the "old" functions: We don't need these anymore as the whole logic at Aptoide changed.

**Comment by baptx** [comment]
@bastei When I give the URL https://facebook.en.aptoide.com/app?store_name=aptoide-web&app_id=64240156 as parameter to the script, it downloads a file named com.facebook.katana 445.0.0.0.103.apk instead of the old version.
If the issue does not happen to you, maybe it is a cache problem on Aptoide server because I downloaded the latest version previously? The issue happens even when removing the aptoide folder.

**Comment by bastei** [comment]
The problem is the way you set the URL as parameter.
When executing
`aptoide https://facebook.en.aptoide.com/app?store_name=aptoide-web&app_id=64240156`
the following happens:
1. `aptoide https://facebook.en.aptoide.com/app?store_name=aptoide-web` is executed in a background job (because it ends with an "&"). As the URL points to the latest version, this one gets downloaded.
2. The variable `app_id` is set to `64240156` in your shell, which has no meaning for the aptoide script.

The right way to set the parameter is wrapping the URL in quotes, so the shell interprets it as a single string:
`aptoide "https://facebook.en.aptoide.com/app?store_name=aptoide-web&app_id=64240156"`

**Comment by baptx** [comment]
@bastei Thanks, it worked with the quotes. Some Linux commands (I don't remember if it is curl, wget or ffmpeg) display a message saying a background job started when we forget the quotes, so when I see this message, I known I missed something.
It would be useful if the aptoide script can display a verbose message like that or a warning / error.

**Pull request merged**
